language: ruby
cache: bundler
sudo: false

rvm:
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.1


gemfile:
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
  - gemfiles/rails6.1.gemfile
  - gemfiles/rails6.2.gemfile

    #matrix:
    #  exclude:
    #    - rvm: 2.4.10
    #      gemfile: gemfiles/rails6.2.gemfile
    #
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
